// Generated by gir (https://github.com/gtk-rs/gir @ b2a1c6f9b362)
// from ../../misc (@ ???)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PolkitAgentListener", sizeof(PolkitAgentListener), alignof(PolkitAgentListener));
    printf("%s;%zu;%zu\n", "PolkitAgentListenerClass", sizeof(PolkitAgentListenerClass), alignof(PolkitAgentListenerClass));
    printf("%s;%zu;%zu\n", "PolkitAgentRegisterFlags", sizeof(PolkitAgentRegisterFlags), alignof(PolkitAgentRegisterFlags));
    return 0;
}
