[package]
name = "polkit-agent"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
glib.workspace = true
gio.workspace = true
gio-sys.workspace = true
polkit-sys.workspace = true
polkit-agent-sys.workspace = true
polkit.workspace = true
