// Generated by gir (https://github.com/gtk-rs/gir @ b2a1c6f9b362)
// from ../misc (@ ???)
// DO NOT EDIT

use crate::{ImplicitAuthorization, ffi};
use glib::translate::*;

glib::wrapper! {
    #[doc(alias = "PolkitActionDescription")]
    pub struct ActionDescription(Object<ffi::PolkitActionDescription, ffi::PolkitActionDescriptionClass>);

    match fn {
        type_ => || ffi::polkit_action_description_get_type(),
    }
}

impl ActionDescription {
    #[doc(alias = "polkit_action_description_get_action_id")]
    #[doc(alias = "get_action_id")]
    pub fn action_id(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_action_id(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_annotation")]
    #[doc(alias = "get_annotation")]
    pub fn annotation(&self, key: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_annotation(
                self.to_glib_none().0,
                key.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_annotation_keys")]
    #[doc(alias = "get_annotation_keys")]
    pub fn annotation_keys(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_none(
                ffi::polkit_action_description_get_annotation_keys(self.to_glib_none().0),
            )
        }
    }

    #[doc(alias = "polkit_action_description_get_description")]
    #[doc(alias = "get_description")]
    pub fn description(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_description(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_icon_name")]
    #[doc(alias = "get_icon_name")]
    pub fn icon_name(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_icon_name(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_implicit_active")]
    #[doc(alias = "get_implicit_active")]
    pub fn implicit_active(&self) -> ImplicitAuthorization {
        unsafe {
            from_glib(ffi::polkit_action_description_get_implicit_active(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_implicit_any")]
    #[doc(alias = "get_implicit_any")]
    pub fn implicit_any(&self) -> ImplicitAuthorization {
        unsafe {
            from_glib(ffi::polkit_action_description_get_implicit_any(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_implicit_inactive")]
    #[doc(alias = "get_implicit_inactive")]
    pub fn implicit_inactive(&self) -> ImplicitAuthorization {
        unsafe {
            from_glib(ffi::polkit_action_description_get_implicit_inactive(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_message")]
    #[doc(alias = "get_message")]
    pub fn message(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_message(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_vendor_name")]
    #[doc(alias = "get_vendor_name")]
    pub fn vendor_name(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_vendor_name(
                self.to_glib_none().0,
            ))
        }
    }

    #[doc(alias = "polkit_action_description_get_vendor_url")]
    #[doc(alias = "get_vendor_url")]
    pub fn vendor_url(&self) -> glib::GString {
        unsafe {
            from_glib_none(ffi::polkit_action_description_get_vendor_url(
                self.to_glib_none().0,
            ))
        }
    }
}
