// Generated by gir (https://github.com/gtk-rs/gir @ b2a1c6f9b362)
// from ../misc (@ ???)
// DO NOT EDIT

use crate::{Identity, ffi};
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "PolkitUnixNetgroup")]
    pub struct UnixNetgroup(Object<ffi::PolkitUnixNetgroup, ffi::PolkitUnixNetgroupClass>) @implements Identity;

    match fn {
        type_ => || ffi::polkit_unix_netgroup_get_type(),
    }
}

impl UnixNetgroup {
    #[doc(alias = "polkit_unix_netgroup_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> glib::GString {
        unsafe { from_glib_none(ffi::polkit_unix_netgroup_get_name(self.to_glib_none().0)) }
    }

    #[doc(alias = "polkit_unix_netgroup_set_name")]
    #[doc(alias = "name")]
    pub fn set_name(&self, name: &str) {
        unsafe {
            ffi::polkit_unix_netgroup_set_name(self.to_glib_none().0, name.to_glib_none().0);
        }
    }

    #[doc(alias = "polkit_unix_netgroup_new")]
    pub fn new(name: &str) -> Self {
        let identify: Identity =
            unsafe { from_glib_full(ffi::polkit_unix_netgroup_new(name.to_glib_none().0)) };
        identify.dynamic_cast().expect("it should always work")
    }

    #[doc(alias = "name")]
    pub fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<F: Fn(&UnixNetgroup) + 'static>(
            this: *mut ffi::PolkitUnixNetgroup,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::name".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_name_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl std::fmt::Display for UnixNetgroup {
    #[inline]
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str(&self.name())
    }
}
