// Generated by gir (https://github.com/gtk-rs/gir @ b2a1c6f9b362)
// from ../misc (@ ???)
// DO NOT EDIT

use crate::{Identity, ffi};
use glib::{
    prelude::*,
    signal::{SignalHandlerId, connect_raw},
    translate::*,
};
use std::boxed::Box as Box_;

glib::wrapper! {
    #[doc(alias = "PolkitUnixUser")]
    pub struct UnixUser(Object<ffi::PolkitUnixUser, ffi::PolkitUnixUserClass>) @implements Identity;

    match fn {
        type_ => || ffi::polkit_unix_user_get_type(),
    }
}

impl UnixUser {
    #[doc(alias = "polkit_unix_user_get_name")]
    #[doc(alias = "get_name")]
    pub fn name(&self) -> Option<glib::GString> {
        unsafe { from_glib_none(ffi::polkit_unix_user_get_name(self.to_glib_none().0)) }
    }

    #[doc(alias = "polkit_unix_user_get_uid")]
    #[doc(alias = "get_uid")]
    pub fn uid(&self) -> i32 {
        unsafe { ffi::polkit_unix_user_get_uid(self.to_glib_none().0) }
    }

    #[doc(alias = "polkit_unix_user_set_uid")]
    #[doc(alias = "uid")]
    pub fn set_uid(&self, uid: i32) {
        unsafe {
            ffi::polkit_unix_user_set_uid(self.to_glib_none().0, uid);
        }
    }

    #[doc(alias = "polkit_unix_user_new")]
    pub fn new(uid: i32) -> Self {
        unsafe {
            let identify: Identity = from_glib_full(ffi::polkit_unix_user_new(uid));
            identify.unsafe_cast()
        }
    }

    #[doc(alias = "polkit_unix_user_new_for_name")]
    pub fn new_for_name(name: &str) -> Result<Self, glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let ret = ffi::polkit_unix_user_new_for_name(name.to_glib_none().0, &mut error);
            if error.is_null() {
                let identify: Identity = from_glib_full(ret);
                let user = identify.unsafe_cast();
                Ok(user)
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    #[doc(alias = "uid")]
    pub fn connect_uid_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_uid_trampoline<F: Fn(&UnixUser) + 'static>(
            this: *mut ffi::PolkitUnixUser,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            unsafe {
                let f: &F = &*(f as *const F);
                f(&from_glib_borrow(this))
            }
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                c"notify::uid".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(
                    notify_uid_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}
